project_planning:
  description: >
    As the project manager, create a concise project plan for researching
    the topic: {topic}.

    Focus on outlining clear objectives, a suitable research approach,
    and a general timeline. Adapt your plan based on the topic type
    (e.g., product/service, concept/idea, process/method, health/lifestyle).

    Complete this planning yourself; do not delegate this core task.
  expected_output: >
    A clear and concise project plan with objectives, methodology outline,
    and timeline for researching: {topic}

research_execution:
  description: >
    Conduct thorough research on the topic: {topic}, adhering to the project plan.

    Gather essential information from credible sources, tailoring your approach
    to the topic type (e.g., specifications for products, theories for concepts,
    evidence for health).
  expected_output: >
    A comprehensive research report detailing key findings and sourced data
    relevant to: {topic}

analysis_execution:
  description: >
    Analyze the research findings for {topic} to extract meaningful insights.

    Provide an expert evaluation, focusing on key insights, comparative analysis,
    and practical implications.
  expected_output: >
    An analytical report containing core insights, evaluations, and actionable
    recommendations based on the research for: {topic}

report_writing:
  description: >
    Synthesize all research and analysis into a professional final report on: {topic}.

    Ensure the report is well-structured, clear, and effectively communicates
    all findings and recommendations. Include an executive summary and references.
  expected_output: >
    A complete, professionally formatted final report integrating all research
    and analysis for: {topic}